extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  file/traces:
    path: /var/lib/otel/traces.jsonl
    flush_interval: 1s
  file/metrics:
    path: /var/lib/otel/metrics.jsonl
    flush_interval: 1s
  otlp/profiles:
    endpoint: pyroscope:4040
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file/traces]
    metrics:
      receivers: [otlp]
      exporters: [file/metrics]
    profiles:
      receivers: [otlp]
      exporters: [otlp/profiles]
